import {
  Container,
  Badge,
  Link,
  List,
  ListItem,
  SimpleGrid,
} from '@chakra-ui/react'
import Layout from '../../components/layouts/article'
import { ExternalLinkIcon } from '@chakra-ui/icons'
import { Title, WorkImage, Meta } from '../../components/work'
import P from '../../components/paragraph'

const Work = () => (
  <Layout title="The Valley">
    <Container>
      <Title>
        The Valley <Badge>2021-2022</Badge>
      </Title>
      <P>
      A Twitch overlay generated by Three.js is a powerful tool that adds a whole new level of visual engagement and interactivity to your Twitch livestream or recorded videos. 

      With Three.js, you can craft visually captivating overlays that captivate your viewers and elevate the overall production value of your content. You can design intricate and immersive landscapes, environments, and scenes that transport your audience to virtual worlds filled with breathtaking visuals.
      </P>

      <List ml={4} my={4}>
        <ListItem>
          <Meta>Platform</Meta>
          <span>Web Browser</span>
        </ListItem>
        <ListItem>
          <Meta>Website</Meta>
          <Link href="https://twitch-stream-wave-overlay.vercel.app/">
            The Valley{' '}
            <ExternalLinkIcon mx="2px" />
          </Link>
        </ListItem>
        <ListItem>
          <Meta>Stack</Meta>
          <span>JavaScript, Three.js</span>
        </ListItem>
      </List>

     
     

      <SimpleGrid columns={2} gap={2}>
        <WorkImage src="/images/works/valley_01.jpg" alt="valley" />
        <WorkImage src="/images/works/valley_02.jpg" alt="valley" />
        <WorkImage src="/images/works/valley_03.png" alt="valley" />

      </SimpleGrid>
    </Container>
  </Layout>
)

export default Work
export { getServerSideProps } from '../../components/chakra'
