import { Container, Heading, SimpleGrid, Divider } from '@chakra-ui/react'
import Script from 'next/script';
import Layout from '../components/layouts/article'
import Section from '../components/section'
import { WorkGridItem } from '../components/grid-item'

import thumbNFM from '../public/images/works/thumbNFM.jpg'
import thumbValley from '../public/images/works/thumbValley.jpg'
import thumbLyriks from '../public/images/works/thumbLyriks.png'

import thumbMargelo from '../public/images/works/Dessert.jpg'

const Works = () => (
  
  <Layout title="Works">
    <Container>
      <Heading as="h3" fontSize={20} mb={4}>
        Works
      </Heading>

      <SimpleGrid columns={[1, 1, 2]} gap={6}>
        <Section>
          <WorkGridItem id="nfmai" title="NFM AI" thumbnail={thumbNFM}>
            An AI that uses text extraction in order to provide underwriters the
            correct information needed for specific guidelines
          </WorkGridItem>
          
        </Section>
        <Section>
          <WorkGridItem
            id="thevalley"
            title="The Valley"
            thumbnail={thumbValley}
          >
            A Twitch overlay generated by Three.js is a dynamic visual element
            that enhances the appearance and interactivity of a Twitch
            livestream or recorded video.
          </WorkGridItem>
        </Section>

        <Section delay={0.1}>
          <WorkGridItem id="lyriks" title="Lyriks" thumbnail={thumbLyriks}>
            Lyriks is a music streaming application that emulates the
            popular features of Spotify while adding unique functionality to
            enhance the user experience. 
          </WorkGridItem>
        </Section>
        <Section delay={0.1}>

        </Section>
      </SimpleGrid>

      <Section delay={0.2}>
        <Divider my={6} />

        <Heading as="h3" fontSize={20} mb={4}>
          3D Web Apps
        </Heading>
      </Section>

      <SimpleGrid columns={[1, 1, 2]} gap={6}>
        <Section delay={0.3}>
          <WorkGridItem id="dessert" thumbnail={thumbMargelo} title="dessert">
          Sticker shop showcases a delightful collection of 3D models

          </WorkGridItem>
        </Section>
                  <div>

          </div>
        {/* <Section delay={0.3}>
          <WorkGridItem
            id="modetokyo"
            thumbnail={thumbModeTokyo}
            title="mode.tokyo"
          >
            The mode magazine for understanding to personally enjoy Japan
          </WorkGridItem>
        </Section> */}
        {/* <Section delay={0.3}>
          <WorkGridItem id="styly" thumbnail={thumbStyly} title="Styly">
            A VR Creative tools for fashion brands
          </WorkGridItem>
        </Section>
      </SimpleGrid>

      <Section delay={0.4}>
        <Divider my={6} />

        <Heading as="h3" fontSize={20} mb={4}>
          Game/Art
        </Heading>
      </Section>

      <SimpleGrid columns={[1, 1, 2]} gap={6}>
        <Section delay={0.5}>
          <WorkGridItem id="pichu2" thumbnail={thumbPichu2} title="Pichu*Pichu">
            Twitter client app for iPhone Safari
          </WorkGridItem>
        </Section> */}
        {/* <Section delay={0.5}>
          <WorkGridItem
            id="freedbtagger"
            thumbnail={thumbFreeDBTagger}
            title="freeDBTagger"
          >
            Automatic audio file tagging tool using FreeDB for Windows
          </WorkGridItem>
        </Section> */}
        {/* <Section delay={0.6}>
          <WorkGridItem id="amembo" thumbnail={thumbAmembo} title="Amembo">
            P2P private file sharing tool with MSN Messenger integration for
            Windows
          </WorkGridItem>
        </Section> */}
      </SimpleGrid>
    </Container>
    <Script 
      src="https://unpkg.com/@splinetool/viewer@0.9.493/build/spline-viewer.js"
      type="module"
      strategy="beforeInteractive" // Load script before the page is interactive
    />
  </Layout>
)

export default Works
export { getServerSideProps } from '../components/chakra'
